spring.application.name=PWPS

# 数据源配置（请根据自己的 MySQL 实际情况修改）
spring.datasource.url=jdbc:mysql://localhost:3306/pwps?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis ??
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example.pwps.entity
mybatis.configuration.map-underscore-to-camel-case=true

# 图片上传路径配置
image.upload.path=picture
